#pragma config(Sensor, in1,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in2,    middleLine,     sensorLineFollower)
#pragma config(Sensor, in3,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in5,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in6,    gyroSensor,     sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, slideEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           intakeMotor,   tmotorVex393, openLoop)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port3,           leftDrive,     tmotorVex393, openLoop, reversed, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port4,           armControl,    tmotorVex393, openLoop)
#pragma config(Motor,  port5,           leftSlide,     tmotorVex393, openLoop, encoder, encoderPort, dgtl11, 1000)
#pragma config(Motor,  port6,           rightSlide,    tmotorVex393, openLoop)
#pragma config(Motor,  port7,           treadMotor,    tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Intakebot - Descore 3 Buckyballs
- This program assumes that you are using the VEX Intakebot in the VEX Toss Up Game.
- This program is designed to descore the Blue Alliance's three Buckyballs that start the match
  on the Bump.
- The robot should start on the Red Hanging Zone start tile.
----------------------------------------------------------------------------------------------------*/

task main()
{
	//Clear encoder values
	SensorValue[leftEncoder]=0;
	SensorValue[rightEncoder]=0;

	//While the left drive encoder is less than 2500 counts,
	//move the robot forward.
	while(SensorValue[leftEncoder] < 2500)
	{
		motor[leftDrive]=127;
		motor[rightDrive]=127;
	}
	//Stop the motors
	motor[leftDrive]=0;
	motor[rightDrive]=0;

	//Clear the encoders
	SensorValue[leftEncoder]=0;
	SensorValue[rightEncoder]=0;

	//Perform a ~90 degree turn
	while(SensorValue[leftEncoder] > -370)
	{
		motor[leftDrive]=-50;
		motor[rightDrive]=50;
	}
	//Stop the motors
	motor[leftDrive]=0;
	motor[rightDrive]=0;

	//Raise the arm above the Bump (until the potentiometer reaches a value of 800)
	while(SensorValue[armPot] < 800)
	{
		motor[armControl] = 75;
	}
	motor[armControl]=0;

	//Push the arm away from the robot in order to clear the Buckyballs
	//(moving the arm away from the bot decreases the arm's encoder values)

	while (SensorValue(slideEncoder) > -500)
	{
		motor[leftSlide]=100;
		motor[rightSlide]=100;
	}
	motor[leftSlide]=0;
	motor[rightSlide]=0;

	//Clear the encoders
	SensorValue[leftEncoder]=0;
	SensorValue[rightEncoder]=0;

	//Drive forward a small amount to ensure the arm is past the bump
	while(SensorValue[leftEncoder] < 150)
	{
		motor[leftDrive]=50;
		motor[rightDrive]=50;
	}
	//Stop the motors
	motor[leftDrive]=0;
	motor[rightDrive]=0;

	//Lower the arm
	while(SensorValue[armPot]>500)
	{
		motor[armControl] = -75;
	}
	motor[armControl]=0;

	//Pull the arm back to the robot and descore 3 Buckyballs
	while (SensorValue(slideEncoder) < 1000)
	{
		motor[leftSlide]=-100;
		motor[rightSlide]=-100;
	}
	motor[leftSlide]=0;
	motor[rightSlide]=0;
	motor[treadMotor]=100;
	while(1){}
}
