#pragma config(Sensor, in1,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in2,    middleLine,     sensorLineFollower)
#pragma config(Sensor, in3,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in5,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in6,    gyroSensor,     sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, slideEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           intakeMotor,   tmotorVex393, openLoop)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port3,           leftDrive,     tmotorVex393, openLoop, reversed, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port4,           armControl,    tmotorVex393, openLoop)
#pragma config(Motor,  port5,           leftSlide,     tmotorVex393, openLoop, encoder, encoderPort, dgtl11, 1000)
#pragma config(Motor,  port6,           rightSlide,    tmotorVex393, openLoop)
#pragma config(Motor,  port7,           treadMotor,    tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows ("JoystickSimple")
#include "JoystickDriver.c"
#define THRESHOLD	10
#define NO_PRESETS	6

int slideEnc,armPoten,liftSet=0;
float slideP,armP;
bool last5, last7;					//Intake,	Drive,	Barrier,Goal,	Goal2,	Catapult
const int presetSlide[NO_PRESETS] =	{240,		240,	240,	1115,	1115,	1115};
const int presetArm[NO_PRESETS] =	{325,		480,	1200,	1700,	1935,	2200};

task main()
	{
	slideP=1;
	armP=0.8;
	SensorValue[slideEncoder]=0;
	while (1==1)
		{
		slideEnc = SensorValue[slideEncoder];
		armPoten = SensorValue[armPot];
		last5 = (bool)joy1Btn(5);
		last7 = (bool)joy1Btn(7);
		getJoystickSettings(joystick); //New joystick values

		if(abs(joystick.joy1_y1) > THRESHOLD || abs(joystick.joy1_x1) > THRESHOLD)
			{
			short temp=(abs(joystick.joy1_y1) > 127-THRESHOLD)*3+1; //1 if turning, 4 if straight
			motor[leftDrive] =  joystick.joy1_y1+joystick.joy1_x1/temp;
			motor[rightDrive] = joystick.joy1_y1-joystick.joy1_x1/temp;
			}
		else
			{
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			}
		/*if(abs(joystick.joy1_y1) > THRESHOLD || abs(joystick.joy1_y2) > THRESHOLD)
			{
			motor[leftDrive] =  joystick.joy1_y1;
			motor[rightDrive] = joystick.joy1_y2;
			}
		else
			{
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			}*/

		if		(joy1Btn(5) == 1 && last5 == 0)	liftSet++;
		else if (joy1Btn(7) == 1 && last7 == 0)	liftSet--;
		if (liftSet<0)				liftSet=0;
		if (liftSet>=NO_PRESETS)	liftSet=NO_PRESETS-1;
		motor[leftSlide]  = (slideEnc+presetSlide[liftSet])*slideP;
		motor[rightSlide] = (slideEnc+presetSlide[liftSet])*slideP;
		motor[armControl] = (-armPoten+presetArm[liftSet])*armP;

		if		(joy1Btn(1) == 1)	motor[treadMotor] = -127;
		else if (joy1Btn(3) == 1)	motor[treadMotor] = 127;
		else						motor[treadMotor] = 0;

		if (joy1Btn(2))			motor[intakeMotor]=0;
		else if (liftSet<=1)	motor[intakeMotor]=100;
		else if (joy1Btn(4))	motor[intakeMotor]=-100;
		else					motor[intakeMotor]= 0;
		}
	}
