#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     compass,        sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define threshold 10
#define joy1_y_def joy1_y1
#define joy1_x_def joy1_x2
#define CLOSED		8
#define OPENED		(-60)

int liftEnc,wristEnc,clawEnc,comp,liftSet=0,clawSet=0;
float liftP,wristP,clawP;


task main()
	{
	liftP=1.2;
	clawP=2;
	wristP=1;
	//Reset encoder values to 0
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorF] = 0;
	nMotorEncoder[motorG] = 0;
	nMotorEncoder[motorH] = 0;
	nMotorEncoder[motorI] = 0;

	//Loop Forever
	while(1 == 1)
		{
		liftEnc = nMotorEncoder[motorI];
		wristEnc = nMotorEncoder[motorB];
		clawEnc = nMotorEncoder[motorA];
		comp = SensorValue[compass];
		//Get the Latest joystick values
		getJoystickSettings(joystick);

		//Driving Control
		if(abs(joystick.joy1_y_def) > threshold || abs(joystick.joy1_x_def) > threshold)
			{
			motor[motorD] = pow(joystick.joy1_y_def,3)/pow(127,2)-pow(joystick.joy1_x_def,3)/pow(127,2);
			motor[motorF] = pow(joystick.joy1_y_def,3)/pow(127,2)-pow(joystick.joy1_x_def,3)/pow(127,2);

			motor[motorE] = pow(joystick.joy1_y_def,3)/pow(127,2)+pow(joystick.joy1_x_def,3)/pow(127,2);
			motor[motorG] = pow(joystick.joy1_y_def,3)/pow(127,2)+pow(joystick.joy1_x_def,3)/pow(127,2);
			}
		else
			{
			motor[motorD] = 0;
			motor[motorF] = 0;
			motor[motorE] = 0;
			motor[motorG] = 0;
			}


		//Scissor Lift Control
		if		(joy1Btn(2) == 1)	liftSet=867;	//Low
		else if (joy1Btn(8) == 1)	liftSet=867;	//Low
		else if (joy1Btn(3) == 1)	liftSet=2086;	//Medium
		else if (joy1Btn(4) == 1)	liftSet=2945;	//High
		else if (joy1Btn(1) == 1)	liftSet=1055;	//Corner
		motor[motorH] = (liftSet-liftEnc)*liftP;
		motor[motorI] = (liftSet-liftEnc)*liftP;
		if (motor[motorH]<-50) motor[motorH]=-50;
		if (motor[motorI]<-50) motor[motorI]=-50;


		//Wrist Motor Control
		motor[motorB] = (180-wristEnc)*wristP;


		//Gripper Motor Control
		if		(joy1Btn(6) == 1) //Close
			clawSet=CLOSED;
		else if (joy1Btn(8) == 1) //Open
			{
			ClearTimer(T4);
			clawSet=OPENED;
			}
		if (time1(T4)>1000)
			clawSet=CLOSED;
		motor[motorA] = (clawSet-clawEnc)*clawP;
		}
	}
