#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    lfR,            sensorLineFollower)
#pragma config(Sensor, in2,    lfM,            sensorLineFollower)
#pragma config(Sensor, in3,    lfL,            sensorLineFollower)
#pragma config(Sensor, I2C_1,  leftArmEnc,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftWheelEnc,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  rightWheelEnc,  sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  rightArmEnc,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           leftWheel,     tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port3,           leftArm,       tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port6,           rightArm,      tmotorVex393, openLoop, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port7,           claw,          tmotorVex269, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "TGRLibrary.c"
#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(60)
#pragma userControlDuration(0)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                         Driver Skills Template
//
// This is a template for the driver skills competition. It is identical in structure to
// the standard competition template except that the two "#pragma' statements above (and
// copied below) adjust the time limits for the competition.
//				#pragma autonomousDuration(0)
//				#pragma userControlDuration(60)
// The autonomous duration for "Driver Skills" is zero; i.e. there is no autonomous phase.
// The user control duration is 60 seconds
//
// NOTE: The above two pragmas only impact the Crystal implementation. For systems using
//       VEXNET, the VEXNET system ignores these statements as it has the durations
//       for the competition built-in.
//
// Whenever this user program is run, the duration is automatically sent to the VEX master
// processor. The master CPU will only accept these commands once per power=on cycle. So, it's
// best to power cycle your VEX to ensure that they get recognized in case you were
// previously running a standard competition program with different durations.
//
// Testing Via Crystals:
// ====================
//
// The procedure to test a Driver Skills program using the crystals is as follows:
//
// 1. Turn off power to the Crystal transmitter/joysticks.
//
// 2. Turn on your VEX so that the Driver Skills program is running.
//
// 3. Driver skills program segment of your program will start running. At the end of 60
//    seconds the VEX Master CPU will turn off the motors.
//
// 4. Repeat the above sequence
//
//
// Testing Via VEXNET Using VEXNET Competition Switch
// ==================================================
//
// The procedure to test a Driver Skills program using VEXNET Competition Switch is as follows:
//
// 1. Set the two switches on the Competition switch to "DISABLE" and "USER CONTROL"
//
// 2. Start the Driver skills program
//
// 3. Set Switch to ENABLE from DISABLE
//
// 4. You need to manually time the 60 second duration.
//
// 5. Set Switch to DISABLE
//
// 6. Repeat from step (3) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
//
// Testing Via VEXNET Using ROBOTC IDE
// ==================================================
//
// It is not necessary to own a VEXNET switch. ROBOTC has a test window that allows the same functionality.
// The test window has three buttons for "DISABLE", "AUTONOMOUS", "USER CONTROL".
//
// 1. Open the ROBOTC Debugger. Then open the "Competition Control" Debugger window.
//
// 2. Start your Driver Skills program running.
//
// 3. Click the "DISABLED" button on the "Competition Control" window.
//
// 4. Click the "USER CONTROL" button on the "Competition Control" window.
//
// 5. You need to manually time the 60 second duration.
//
// 6. Click the "DISABLED" button on the "Competition Control" window.
//
// 7. Repeat from step (4) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// The "Driver Skills" competition has no autonomous phase. Simply leave the following
// placeholder.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  StartTask(armTurnPos);
	navigateTo(-700,-700);
	clawOpen();
	navigateTo(1000,1000);
	StopTask(armTurnPos);
	StartTask(armTile);
	wait1Msec(1000);
	clawClose();
	motor[claw]=-30;
	wait1Msec(1000);
	StopTask(armTile);
	StartTask(arm11);
	wait1Msec(1000);
	navigateTo(100,100);
	motor[leftWheel]=60;
	motor[rightWheel]=60;

  navigateTo(900, -900);
  navigateTo(1500, 1500);
  clawOpen();
  navigateTo(-900, -900);
  StopTask(arm11);
  StartTask(armTurnPos);
  navigateTo(-500, 500);
  navigateTo(3000, 3000);
  clawClose();
  StopTask(armTurnPos);
  StartTask(arm20);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	  LCDinit();
	// User control code here, inside the loop
long armloc=0;
nMotorEncoder[leftArm]=0;
nMotorEncoder[rightArm]=0;
short last=0;
	while (true)
	{

	  clearLCDLine(0);
	  clearLCDLine(1);
	  LCDdisplayn(nMotorEncoder[leftArm], 1);
	  LCDdisplayn(armloc, 0);
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................

	  motor[leftWheel]=vexRT[Ch3]+vexRT[Ch4];
	  motor[rightWheel]=vexRT[Ch3]-vexRT[Ch4];
	  if(abs(vexRT[Ch2])<5)
	  {
	    motor[leftArm]=10;
	    motor[rightArm]=10;
	  }
	  else
	  {
	  motor[leftArm]=vexRT[Ch2];
	  motor[rightArm]=vexRT[Ch2];
	}
	if(vexRT[Btn6U]==1)
	{
	  motor[claw]=-100;
	  last=1;
}
else if(vexRT[Btn6D]==1)
{
  motor[claw]=100;
  last=0;
}
else if(last==1)
{
  motor[claw]=-30;
}
else
{
  motor[claw]=0;
}
	}
}
