#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     compass,        sensorVirtualCompass)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     fr_drive,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     fl_drive,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     br_drive,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     bl_drive,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     r_lift,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     l_lift,        tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "Daniel_FTC_functions.c"


task main()
	{
	startup();


	gripper(close);
	wrist(150);
	turn(-45);
	forward(4300);
	lift(2800);
	turn(90);
	forward(3050);
	gripper(open); //Top Ring 1
	reverse(3050);
	gripper(close);
	lift(2200);
	forward(3050);
	gripper(open); //Middle Ring 1
	reverse(3050);
	gripper(close);
	lift(950);
	forward(2950);
	gripper(open); //Bottom Ring 1
	reverse(3050);
	gripper(close);
	turn(-90);
	forward(2800);
	turn(-45);
	gripper(open); //corner ring 1



	wait(30000);
	wait(30000);
	}

/*
TO DO

use encoder instead of time
use absolute compass
	argument+=target

*/
